import { auth,db,SETTINGS,ref,get,update,requireUser,signOut,$,$$,esc,days,now,dateText,statusOf,cleanPhone } from "./shared.js";
let customers={},filter="all",ctx,adminPin=sessionStorage.getItem("vasukiAdminPin")||"";
function getAdminPin(){if(!adminPin)adminPin=prompt("Enter Vasuki owner/admin PIN to manage subscriptions:")||"";if(adminPin)sessionStorage.setItem("vasukiAdminPin",adminPin);return adminPin}
async function api(path,options={}){const response=await fetch(`${SETTINGS.apiBase}${path}`,{...options,headers:{"Content-Type":"application/json","X-Admin-Pin":getAdminPin(),...(options.headers||{})}});const data=await response.json();if(!response.ok)throw new Error(data.error||"Subscription service error");return data}
async function publicSubscription(cardId){try{const response=await fetch(`${SETTINGS.apiBase}/api/card-subscription/${encodeURIComponent(cardId)}`,{cache:"no-store"});if(!response.ok)throw new Error();return response.json()}catch{return null}}
async function boot(){ctx=await requireUser(["owner","admin","support"]);await refresh()}
async function refresh(){const [c,p,t]=await Promise.all([get(ref(db,"customers")),get(ref(db,"payments")),get(ref(db,"supportTickets"))]);const raw=c.val()||{},migration={};customers={};for(const [key,value] of Object.entries(raw)){if(value.cardId&&value.profile){customers[key]=value;continue}const profile={name:value.name||"",business:value.business||value.businessName||"",phone:value.phone||"",whatsapp:value.whatsapp||value.phone||"",publicEmail:value.email||"",website:value.website||"",location:value.location||"",profileImage:value.profileImage||"",tagline:value.tagline||"Digital Business Card",about:value.about||value.services||""};customers[key]={...value,cardId:key,profile,legacy:true};migration[`publishedProfiles/${key}`]=profile;migration[`publicSubscriptions/${key}`]={status:"active",lifetime:true,plan:"legacy_lifetime"};}if(Object.keys(migration).length&&ctx.role!=="support")await update(ref(db),migration);await Promise.all(Object.values(customers).map(async customer=>customer.apiSubscription=await publicSubscription(customer.cardId)));renderCustomers();renderPayments(p.val()||{});renderTickets(t.val()||{})}
function cardState(c){if(c.apiSubscription?.lifetime)return "lifetime";if(c.apiSubscription)return c.apiSubscription.status==="active"?statusOf(c.apiSubscription.expiresAt):"expired";return statusOf(c.subscription?.expiresAt)}
function renderCustomers(){let rows=[],counts={active:0,soon:0,expired:0,lifetime:0};Object.entries(customers).forEach(([uid,c])=>{const s=cardState(c);counts[s]=(counts[s]||0)+1;if(filter!=="all"&&filter!==s)return;const expiry=s==="lifetime"?"Lifetime":dateText(c.apiSubscription?.expiresAt||c.subscription?.expiresAt);rows.push(`<tr><td><strong>${esc(c.profile?.name)}</strong><br><small>${esc(c.profile?.business)}</small></td><td>${esc(c.cardId)}</td><td>${esc(c.profile?.phone)}</td><td><span class="badge ${s==='lifetime'?'active':s}">${s==='lifetime'?'LEGACY LIFETIME':s}</span></td><td>${expiry}</td><td>${s==='lifetime'?'No recharge required':`<button class="gold renew" data-uid="${esc(uid)}">+365 days</button>`} <a class="btn light" href="https://wa.me/${cleanPhone(c.profile?.phone)}?text=${encodeURIComponent(`Hello, your Vasuki NFC card ${c.cardId} subscription needs renewal.`)}" target="_blank">WhatsApp</a></td></tr>`)});$("#rows").innerHTML=rows.join("")||'<tr><td colspan="6">No customers in this filter.</td></tr>';$("#total").textContent=Object.keys(customers).length;$("#active").textContent=counts.active+counts.lifetime;$("#follow").textContent=counts.soon+counts.expired;$$('.renew').forEach(button=>button.onclick=()=>renew(button.dataset.uid))}
async function renew(uid,paymentId){if(ctx.role==='support'){alert('Support members cannot activate subscriptions.');return}const c=customers[uid];try{const result=await api(`/api/card-admin/subscriptions/${encodeURIComponent(c.cardId)}/renew`,{method:"POST",body:"{}"});const expiresAt=result.subscription.expiresAt,historyId=String(now());const changes={[`customers/${uid}/subscription`]:{status:"active",startedAt:now(),expiresAt,plan:"annual",price:SETTINGS.annualPrice},[`publicSubscriptions/${c.cardId}`]:{status:"active",expiresAt},[`renewalHistory/${uid}/${historyId}`]:{days:365,amount:paymentId?SETTINGS.annualPrice:0,approvedBy:ctx.user.uid,createdAt:now()}};if(paymentId)changes[`payments/${paymentId}/status`]="approved";await update(ref(db),changes);await refresh()}catch(error){alert(error.message)}}
function renderPayments(data){const rows=Object.entries(data).filter(([,p])=>p.status==='pending').map(([id,p])=>`<tr><td>${esc(p.cardId)}</td><td>${esc(p.transactionId)}</td><td>₹${Number(p.amount||0)}</td><td>${dateText(p.createdAt)}</td><td><button class="gold approve" data-id="${id}" data-uid="${esc(p.uid)}">Approve + 365 days</button></td></tr>`);$("#payments").innerHTML=rows.join("")||'<tr><td colspan="5">No pending payments.</td></tr>';$$('.approve').forEach(button=>button.onclick=()=>{if(confirm('Confirm only after checking payment in your bank/UPI account. Continue?'))renew(button.dataset.uid,button.dataset.id)})}
function renderTickets(data){const items=Object.entries(data).filter(([,t])=>t.status==='open').map(([id,t])=>`<div class="faq"><strong>${esc(t.cardId)}</strong> — ${esc(t.issue)} <button class="light resolve" data-id="${id}" style="float:right">Resolve</button></div>`);$("#tickets").innerHTML=items.join("")||'<p class="muted">No open tickets.</p>';$$('.resolve').forEach(button=>button.onclick=async()=>{await update(ref(db,`supportTickets/${button.dataset.id}`),{status:'resolved',resolvedAt:now(),resolvedBy:ctx.user.uid});refresh()})}
$("#addBtn").onclick=()=>$("#addDialog").showModal();$("#closeAdd").onclick=()=>$("#addDialog").close();
$("#addForm").onsubmit=async event=>{event.preventDefault();if(ctx.role!=='owner'&&ctx.role!=='admin'){alert('No permission.');return}if(!getAdminPin()){alert('Admin PIN is required.');return}const uid=$("#uid").value.trim(),cardId=$("#cardId").value.trim().toLowerCase().replace(/[^a-z0-9_-]/g,''),valid=Number($("#validity").value),existing=await get(ref(db,`cardOwners/${cardId}`));if(existing.exists()){alert('Card ID already exists.');return}const profile={name:$("#customerName").value.trim(),phone:$("#customerPhone").value.trim(),whatsapp:$("#customerPhone").value.trim(),business:$("#customerBusiness").value.trim(),publicEmail:'',website:'',location:'',profileImage:'',tagline:'',about:''};try{const subscription=await api('/api/card-admin/subscriptions',{method:'POST',body:JSON.stringify({cardId,plan:'first_year_free',customerName:profile.name,phone:profile.phone})});const expiresAt=subscription.subscription.expiresAt,status='active';await update(ref(db),{[`roles/${uid}`]:'customer',[`cardOwners/${cardId}`]:uid,[`customers/${uid}`]:{cardId,profile,subscription:{status,startedAt:now(),expiresAt,plan:'first_year_free',price:0},createdAt:now()},[`publishedProfiles/${cardId}`]:profile,[`publicSubscriptions/${cardId}`]:{status,expiresAt},[`scanCounts/${cardId}`]:0});$("#addDialog").close();event.target.reset();refresh()}catch(error){alert(error.message)}};
$$('.filter').forEach(button=>button.onclick=()=>{filter=button.dataset.filter;renderCustomers()});$("#logout").onclick=()=>signOut(auth).then(()=>location.href='login.html');boot();
