import { auth,db,SETTINGS,ref,get,update,requireUser,signOut,$,$$,esc,now,dateText,statusOf,cleanPhone,registerSW } from "./shared.js";
let customers={},filter="all",ctx,adminPin=sessionStorage.getItem("vasukiAdminPin")||"";
const waPhone=value=>{const digits=cleanPhone(value);return /^\d{10}$/.test(digits)?`91${digits}`:digits};
function getAdminPin(){if(!adminPin)adminPin=prompt("Enter Vasuki owner/admin PIN to manage subscriptions:")||"";if(adminPin)sessionStorage.setItem("vasukiAdminPin",adminPin);return adminPin}
async function api(path,options={}){const response=await fetch(`${SETTINGS.apiBase}${path}`,{...options,headers:{"Content-Type":"application/json","X-Admin-Pin":getAdminPin(),...(options.headers||{})}});const data=await response.json();if(!response.ok)throw new Error(data.error||"Subscription service error");return data}
async function publicSubscription(cardId){try{const response=await fetch(`${SETTINGS.apiBase}/api/card-subscription/${encodeURIComponent(cardId)}`,{cache:"no-store"});if(!response.ok)throw new Error();return response.json()}catch{return null}}
async function boot(){ctx=await requireUser(["owner","admin","support"]);if(ctx.role==="support")$("#addBtn").classList.add("hidden");await refresh()}
async function refresh(){const [c,p,t]=await Promise.all([get(ref(db,"customers")),ctx.role==="support"?Promise.resolve(null):get(ref(db,"payments")),get(ref(db,"supportTickets"))]);const raw=c.val()||{},migration={};customers={};for(const [key,value] of Object.entries(raw)){if(value.cardId&&value.profile){customers[key]=value;continue}const social=value.social||value.socials||value.socialLinks||{};const profile={name:value.name||value.fullName||"",business:value.business||value.businessName||value.company||"",phone:value.phone||value.mobile||"",whatsapp:value.whatsapp||value.whatsApp||value.phone||value.mobile||"",publicEmail:value.publicEmail||value.email||"",website:value.website||"",location:value.location||value.address||"",profileImage:value.profileImage||value.photo||"",tagline:value.tagline||"Digital Business Card",about:value.about||value.services||"",instagram:value.instagram||value.instagramUrl||social.instagram||"",facebook:value.facebook||value.facebookUrl||social.facebook||"",linkedin:value.linkedin||value.linkedIn||value.linkedinUrl||social.linkedin||social.linkedIn||"",youtube:value.youtube||value.youTube||value.youtubeUrl||social.youtube||social.youTube||"",theme:value.theme||"classic"};customers[key]={...value,cardId:key,profile,legacy:true};migration[`publishedProfiles/${key}`]=profile;migration[`publicSubscriptions/${key}`]={status:"active",lifetime:true,plan:"legacy_lifetime",verified:true};}if(Object.keys(migration).length&&ctx.role!=="support")await update(ref(db),migration);await Promise.all(Object.values(customers).map(async customer=>customer.apiSubscription=await publicSubscription(customer.cardId)));renderCustomers();renderPayments(p?.val?.()||{});renderTickets(t.val()||{})}
function cardState(c){if(c.apiSubscription?.lifetime)return "lifetime";if(c.apiSubscription)return c.apiSubscription.status==="active"?statusOf(c.apiSubscription.expiresAt):"expired";return statusOf(c.subscription?.expiresAt)}
function renderCustomers(){
 let rows=[],counts={active:0,soon:0,expired:0,lifetime:0};
 Object.entries(customers).forEach(([uid,c])=>{
  const s=cardState(c);counts[s]=(counts[s]||0)+1;
  if(filter!=="all"&&filter!==s)return;
  const expiry=s==="lifetime"?"Lifetime":dateText(c.apiSubscription?.expiresAt||c.subscription?.expiresAt);
  const lifetimeLabel=c.apiSubscription?.plan==="legacy_lifetime"||c.legacy?"LEGACY LIFETIME":"PAID LIFETIME";
  const statusLabel=s==="lifetime"?lifetimeLabel:s.toUpperCase();
  const renewAction=s==="lifetime"?"No recharge required":ctx.role==="support"?"Owner approval required":`<button class="gold renew" data-uid="${esc(uid)}">+365 days</button>`;
  rows.push(`<tr><td><strong>${esc(c.profile?.name)}</strong><br><small>${esc(c.profile?.business)}</small></td><td>${esc(c.cardId)}</td><td>${esc(c.profile?.phone)}</td><td><span class="badge ${s==='lifetime'?'active':s}">${statusLabel}</span></td><td>${expiry}</td><td>${renewAction} <a class="btn light" href="https://wa.me/${waPhone(c.profile?.phone)}?text=${encodeURIComponent(`Hello, your Vasuki NFC card ${c.cardId} subscription needs renewal.`)}" target="_blank" rel="noopener">WhatsApp</a></td></tr>`);
 });
 $("#rows").innerHTML=rows.join("")||'<tr><td colspan="6">No customers in this filter.</td></tr>';
 $("#total").textContent=Object.keys(customers).length;$("#active").textContent=counts.active+counts.lifetime;$("#follow").textContent=counts.soon+counts.expired;
 $$('.renew').forEach(button=>button.onclick=()=>renew(button.dataset.uid));
}
async function renew(uid,paymentId){if(ctx.role==='support'){alert('Support members cannot activate subscriptions.');return}const c=customers[uid];try{const result=await api(`/api/card-admin/subscriptions/${encodeURIComponent(c.cardId)}/renew`,{method:"POST",body:"{}"});const subscription={...result.subscription,status:"active",lifetime:false,verified:true,startedAt:now(),price:SETTINGS.annualPrice};const historyId=String(now());const changes={[`customers/${uid}/subscription`]:subscription,[`publicSubscriptions/${c.cardId}`]:subscription,[`renewalHistory/${uid}/${historyId}`]:{days:365,amount:paymentId?SETTINGS.annualPrice:0,approvedBy:ctx.user.uid,createdAt:now()}};if(paymentId)changes[`payments/${paymentId}/status`]="approved";await update(ref(db),changes);await refresh()}catch(error){alert(error.message)}}
function renderPayments(data){const rows=Object.entries(data).filter(([,p])=>p.status==='pending').map(([id,p])=>`<tr><td>${esc(p.cardId)}</td><td>${esc(p.transactionId)}</td><td>₹${Number(p.amount||0)}</td><td>${dateText(p.createdAt)}</td><td><button class="gold approve" data-id="${id}" data-uid="${esc(p.uid)}">Approve + 365 days</button></td></tr>`);$("#payments").innerHTML=rows.join("")||'<tr><td colspan="5">No pending payments.</td></tr>';$$('.approve').forEach(button=>button.onclick=()=>{if(confirm('Confirm only after checking payment in your bank/UPI account. Continue?'))renew(button.dataset.uid,button.dataset.id)})}
function renderTickets(data){const items=Object.entries(data).filter(([,t])=>t.status==='open').map(([id,t])=>`<div class="faq"><strong>${esc(t.cardId)}</strong> — ${esc(t.issue)} <button class="light resolve" data-id="${id}" style="float:right">Resolve</button></div>`);$("#tickets").innerHTML=items.join("")||'<p class="muted">No open tickets.</p>';$$('.resolve').forEach(button=>button.onclick=async()=>{await update(ref(db,`supportTickets/${button.dataset.id}`),{status:'resolved',resolvedAt:now(),resolvedBy:ctx.user.uid});refresh()})}
$("#addBtn").onclick=()=>$("#addDialog").showModal();$("#closeAdd").onclick=()=>$("#addDialog").close();
$("#addForm").onsubmit=async event=>{event.preventDefault();if(ctx.role!=="owner"&&ctx.role!=="admin"){alert("No permission.");return}if(!getAdminPin()){alert("Admin PIN is required.");return}const submit=event.submitter;submit.disabled=true;const payload={email:$("#customerEmail").value.trim(),password:$("#customerPassword").value,cardId:$("#cardId").value.trim().toLowerCase().replace(/[^a-z0-9_-]/g,""),customerName:$("#customerName").value.trim(),phone:$("#customerPhone").value.trim(),business:$("#customerBusiness").value.trim()};try{const result=await api("/api/card-admin/customers",{method:"POST",body:JSON.stringify(payload)});$("#addDialog").close();event.target.reset();await refresh();alert(`Customer created successfully.\nCard ID: ${result.cardId}\nLogin: ${result.email}\nFirst year is active.`)}catch(error){alert(error.message)}finally{submit.disabled=false}};
$$('.filter').forEach(button=>button.onclick=()=>{filter=button.dataset.filter;renderCustomers()});$("#logout").onclick=()=>signOut(auth).then(()=>location.href='login.html');boot();
let ownerInstallPrompt=null;
const installOwner=$("#installOwner");
const ownerStandalone=window.matchMedia('(display-mode: standalone)').matches||window.navigator.standalone===true;
registerSW();
window.addEventListener('beforeinstallprompt',event=>{event.preventDefault();ownerInstallPrompt=event;if(!ownerStandalone)installOwner.classList.remove('hidden')});
installOwner.onclick=async()=>{if(!ownerInstallPrompt)return;ownerInstallPrompt.prompt();await ownerInstallPrompt.userChoice;ownerInstallPrompt=null;installOwner.classList.add('hidden')};
window.addEventListener('appinstalled',()=>installOwner.classList.add('hidden'));
